name: Cloud Build Python APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取自身代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 拉取第三方代码文件夹 third_lib
      - name: Pull third-party source code
        run: |
          git clone https://github.com/kriou/Box.git third_lib
          cd third_lib
          git checkout main

      - name: Install Buildozer
        run: |
          python3 -m pip install --upgrade pip
          pip3 install buildozer

      - name: Accept Android SDK Licenses
        run: |
          buildozer android sdk
          SDK_DIR="$HOME/.buildozer/android/platform/android-sdk"
          yes | $SDK_DIR/cmdline-tools/latest/bin/sdkmanager --licenses
          yes | $SDK_DIR/cmdline-tools/latest/bin/sdkmanager "build-tools;37.0.0"

      - name: Cache buildozer env
        uses: actions/cache@v3
        with:
          path: |
            ~/.buildozer
            ./bin
          key: ${{ runner.os }}-bz-${{ hashFiles('buildozer.spec') }}

      - name: Build APK with verbose log
        run: buildozer android debug

      - name: Upload compiled APK
        uses: actions/upload-artifact@v4
        with:
          name: Output-APK
          path: bin/*.apk
